apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-bootcamp
  labels:
    app: kubernetes-bootcamp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubernetes-bootcamp
  template:
    metadata:
      labels:
        app: kubernetes-bootcamp
    spec:
      containers:
      - name: kubernetes-bootcamp
        image: gcr.io/google-samples/kubernetes-bootcamp:v1
        volumeMounts:
        - name: pv-volume
          mountPath: .github/K8s/image/volumes/mypvc.yaml
      volumes:
      - name: pv-volume
        persistentVolumeClaim:
          claimName: mypvc
