# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  Vagrant.configure("2") do |config|
    config.vm.box = "my-box"
    config.vm.provider "vmware_desktop" do |v|
      v.gui = true
    end
  end

  # Define the VM
  config.vm.define "centos_server" do |server|
    # Specify the Vagrant box to use
    server.vm.box = "centos/7"
    # vagrant-vmware-desktop Virtualbox provisioner
    config.vm.provider "vmware_desktop" do |vmware|
      vmware.vmx["memsize"] = "2048"
      vmware.vmx["numvcpus"] = "1"
    end
  end
  
  # Start provisioning
  $script = <<-SCRIPT
  echo I am provisioning...
  date > /etc/vagrant_provisioned_at
  SCRIPT

  config.vm.provision "shell", inline: $script

end
